services:
  shop:
    image: dockware/shopware-essentials:1.1.0
    container_name: shop
    ports:
      - "80:80"
      - "3306:3306"
      - "443:443"
      - "5173:5173"
    environment:
      - PHP_VERSION=8.3
    volumes:
      - ./:/var/www/html
      - db-data:/var/lib/mysql

volumes:
  db-data: